### ISSUE TITLE
When using UDT Enumeration, the SQL Data Record Constructor does not respect global string default

### ISSUE THREAD

**Issue by bkjuice** [bkjuice/teaq#9]
Test Name:	..SelfMatch
Test FullName:	..RetursSelfMatch
Test Source:	...adIntegrationRepositoryTests.cs : line 55
Test Outcome:	Failed
Test Duration:	0:00:00.0018778

Result StackTrace:	
at Microsoft.SqlServer.Server.SqlMetaData.Construct(String name, SqlDbType dbType, Boolean useServerDefault, Boolean isUniqueKey, SortOrder columnSortOrder, Int32 sortOrdinal)
   at Teaq.UdtTypeEnumerator`1.CreateMetadata(String columnName, ColumnDataType columnType)
   at Teaq.UdtTypeEnumerator`1.GetColumnMetadata(PropertyDescription[] propsInScope, IDataModel model)
   at Teaq.UdtTypeEnumerator`1..ctor(IEnumerable`1 items, IDataModel model)
   at ...rationRepository.<...adRequest>d__4.MoveNext() in ..ionRepository.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ..onRepositoryTests.<..sSelfMatch>d__1.MoveNext() in ..rationTests\LeadIntegrationRepositoryTests.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Result Message:	
Test method ..ursSelfMatch threw exception: 
System.ArgumentException: The dbType VarChar is invalid for this constructor.

**Comment by bkjuice** [comment]
Fixed and unit tested, requires additional integration testing.
